language: python
python:
  - "2.7"
  - "3.5"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ffmpeg libavcodec-extra-53
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
# command to run tests
script: nosetests
sudo: true
